#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2020  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

# ** WARNING **
# This file is auto-generated by the update_version.py script.
# ** WARNING **

version_str = "UNKNOWN"
version_tuple = (0, 0, 0, 0)

git_hash = "UNKNOWN"
git_describe = "UNKNOWN"
git_msg = """\
commit UNKNOWN
Author: UNKNOWN
Date:   UNKNOWN

    UNKNOWN

    Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>

"""
