#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2020  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

# ** WARNING **
# This file is auto-generated by the update_version.py script.
# ** WARNING **

version_str = "0.0.2.post66"
version_tuple = (0, 0, 2, 66)
try:
    from packaging.version import Version as V
    pversion = V("0.0.2.post66")
except ImportError:
    pass

git_hash = "c0b734e6d373fcffd0522acdd102814bcefb626a"
git_describe = "v0.0.2-66-gc0b734e"
git_msg = """\
commit c0b734e6d373fcffd0522acdd102814bcefb626a
Author: Tim 'mithro' Ansell <me@mith.ro>
Date:   Fri Feb 19 13:05:20 2021 -0800

    Improve the warning message when falling back to the textX.

    Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>

"""
