name: 🧰 Checkout
description: "Checkout the git repository correctly"

runs:
  using: "composite"

  steps:
  - name: 🧰 Checkout
    uses: actions/checkout@v2
    with:
      # Always clone the full depth so git-describe works.
      fetch-depth: 0
      submodules: true
