name: Install from

on:
  push:
  pull_request:


jobs:

  GitHub:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-20.04]
      fail-fast: false

    name: GitHub
    runs-on: ${{ matrix.os }}

    steps:
    - name: 🐍 Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install pip
      run: |
        pip install --upgrade pip

    - name: Install package's system dependencies (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake default-jre-headless uuid-dev libantlr4-runtime-dev

    - name: Install package's system dependencies (Mac OS X)
      if: startsWith(matrix.os, 'macos')
      run: |
        true

    - name: Install package's system dependencies (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        true

    - name: Test installation
      shell: bash
      run: |
        pip install git+https://github.com/${GITHUB_REPOSITORY}.git@${GITHUB_SHA}#egg=fasm

    - name: Run Smoke Test
      run: |
        fasm --help
