name: Install from

on:
  push:
  pull_request:


jobs:

  GitHub:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: '${{ github.repository }}/.github/workflows/system-setup@${{ github.sha }}'
      with:
        os: ${{ matrix.os }}
        git-checkout: false

    - name: Test installation
      shell: bash
      run: |
        pip install git+https://github.com/${GITHUB_REPOSITORY}.git@${GITHUB_SHA}#egg=fasm

    - name: Run smoke test
      run: |
        fasm --help

#    - name: Run tests against installed version
#      run: |
#        cd tests; python test_simple.py

  Checkout:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        cmd:
          - python setup.py install
          - pip install .
          - pip install -e .    # Editable install
      fail-fast: false

    name: Checkout with '${{ matrix.cmd }}'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: '${{ github.repository }}/.github/workflows/system-setup@${{ github.sha }}'
      with:
        os: ${{ matrix.os }}

    - name: Install using '${{ matrix.cmd }}'
      run: |
        ${{ matrix.cmd }}

    - name: Run smoke test
      run: |
        fasm --help

    - name: Run tests against installed version
      run: |
        cd tests; python test_simple.py

  Wheel:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: '${{ github.repository }}/.github/workflows/system-setup@${{ github.sha }}'
      with:
        os: ${{ matrix.os }}

    - name: Build wheel
      run: |
        python setup.py bdist_wheel

    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: fasm
        path: dist

    - name: Install wheel
      run: |
        pip install dist/*.whl

    - name: Run smoke test
      run: |
        fasm --help

    - name: Run tests against installed version
      run: |
        cd tests; python test_simple.py

  make-env:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    name: make-env (Conda)
    runs-on: ${{ matrix.os }}

    steps:
    - uses: '${{ github.repository }}/.github/workflows/checkout@${{ github.sha }}'

    - name: Run tests
      run: |
        make tests
