# Copyright (C) 2017-2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

on:
  push:
  pull_request:

name: Functionality
jobs:

  functionality:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        antlr_runtime_type: [static, shared]
        include:
          - { python-version: 3.5, TOXENV: py35 }
          - { python-version: 3.6, TOXENV: py36 }
          - { python-version: 3.7, TOXENV: py37 }
          - { python-version: 3.8, TOXENV: py38 }
          - { python-version: 3.9, TOXENV: py39 }
      fail-fast: false

    name: Functionality on Python ${{ matrix.python-version }} (with ${{ matrix.antlr_runtime_type}} antlr)

    steps:
    - includes: /system-setup
      with:
        development-tools: true
        python-version: ${{ matrix.python-version }}

    - name: Run Tests
      run: |
        ANTLR4_RUNTIME_TYPE=${{ matrix.antlr_runtime_type }} tox -e ${{ matrix.TOXENV }}
